config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :positions, only: [:index, :new, :create, :edit, :show, :update, :destroy]
  resources :selections, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :companies, only: [:index, :show]

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :stacks, only: [:index]

  root 'top#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :lot, :buy_price, :buy_reason, :sell_price, :sell_percent ,:sell_reason, presence: true

  belongs_to :user
  belongs_to :stack

  #証券コードを表示
  def position_code(stack_code)
    stack_code.slice(0,4)
  end

  # 会社名を表示
  def position_company(stack_company)
    stack_company.slice(5..15)
  end

  # csvダウンロード用
  def self.to_csv
    CSV.generate do |csv|
      csv << csv_column_positions
      all.each do |position|
        csv << position.csv_column_value_positions
      end
    end
  end

  # csvのヘッダーの並び順
  def self.csv_column_positions
    ["企業", "株数", "買値", "買い理由", "売却価格希望", "売却理由"]
  end

  # csvの並び順
  def csv_column_value_positions
    [name, lot, buy_price, buy_reason, sell_price, sell_reason]
  end

  # 未使用 - APIデータだと使用不可？
  def price_calcultion(stock_price, buy_price, lot)
    (stock_price - buy_price) * lot
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_position, only: [:edit, :show, :update, :destroy]
  def index
    @positions = Position.all
    @stacks = Stack.all
    @users = User.all
    @position_csv = current_user.positions
    # CSV出力
    respond_to do |format|
      format.html
      format.csv {send_data @position_csv.to_csv}
    end
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(positions_params)
    @position.user_id = current_user.id
    if @position.save
      redirect_to positions_path, notice: "ポートフォリオを作成しました。"
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @stacks = Stack.all
    @positions = Position.all
  end

  def update
    if @position.update(positions_params)
      redirect_to positions_path, notice: "ポジションを更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @position.destroy
    redirect_to positions_path, notice: "ポートフォリオを削除しました。"
  end

  private
  def positions_params
    params.require(:position).permit(:name, :lot, :buy_price, :buy_reason, :buy_image, :sell_price, :sell_percent, :high_price_per, :sell_reason)
  end

  def set_position
    @position = Position.find(params[:id])
  end
end

# 例外処理
# raise
# 強制停止
# binding.pry

app/helpers/positions_helper.rb
module PositionsHelper
  def color(position_length)
    colors = []
    count = 0
    i = 0
    color = ['orange','lime','yellow','blue','green','aqua','purple','navy','teal','fuchsia','maroon','red']
    while count < position_length
      if count == 12
        i = 0
      end
      colors.push(color[i])
      i+=1
      count+=1
    end
    colors.each { |color| print color }
  end
end

app/views/positions/_form.html.erb
<div class="thumbnail">
  <%= form_for(@position) do |f| %>
    <% if @position.errors.any? %>
      <div id="error_explanation" >
        <!-- バリデーションのエラー件数 -->
        <h2><%= @position.errors.count %>件のエラーがあります。</h2>

        <ul>
          <% @position.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label "銘柄", class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.select :name, Stack.all.map{|t| ["#{t.code} #{t.company}", "#{t.code}　#{t.company}"]},{},{class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "株数", class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.number_field :lot, min: "1", class: "form-control", placeholder: "lot" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "購入価格", class: "col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.number_field :buy_price, min: "1", class: "form-control", placeholder: "buy_price" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "購入理由", class: "col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.text_field :buy_reason, class: "form-control", placeholder: "buy_reason" %>
        </div>
      </div>
      <!-- <div class="form-group"> -->
        <!-- <%= f.label "購入理由（画像）", class: "col-sm-4 control-label"  %> -->
        <!-- <div class="col-sm-8"> -->
          <!-- <%= f.file_field :buy_image, class: " form-control" %> -->
        <!-- </div> -->
      <!-- </div> -->
      <div class="center_line">
        <h4>売り基準</h4>
      </div>
      <div class="form-group">
        <%= f.label "売却価格（予定）", class: "col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.number_field :sell_price, min: "1", class: "form-control", placeholder: "sell_price" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "比率売却価格（％）", class: "col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.number_field :sell_percent, min: "1", class: "form-control", placeholder: "sell_percent" %>
        </div>
      </div>
      <!-- <div class="form-group"> -->
        <!-- <%= f.label "（購入後の）最高値後からの騰落率（％）", class: "col-sm-4 control-label"  %> -->
        <!-- <div class="col-sm-8"> -->
          <!-- <%= f.number_field :high_price_per, min: "1", max: "99", class: " form-control" %> -->
        <!-- </div> -->
      <!-- </div> -->
      <div class="form-group">
        <%= f.label "売却理由", class: "col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.text_field :sell_reason, class: "form-control", placeholder: "sell_reason" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit "保存", class: "btn btn-primary"  %>
          <%= link_to "戻る", positions_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/positions/edit.html.erb
<div class="container">
  <div class="line_header">
    <h3>ポジションを変更する</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/positions/index.html.erb
<% provide(:title, "｜ ポートフォリオ")%>
<!-- 個人のみ閲覧可能 -->
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p class="text-center"><%= notice %></p>
      <div class="line_header">
        <h3><%= current_user.name %>さんのポートフォリオ</h3>
      </div>
      <div class="thumbnail position_table">
        <p><%= link_to "新規の株式取引を記録をする", new_position_path, class: "btn btn-primary position_add" %></p>
        <p>現在のポジション一覧</p>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="text-center">証券コード</th>
                <th class="text-center">銘柄</th>
                <th class="text-center">保有株数</th>
                <th class="text-center">買付け価格</th>
                <th class="text-center">株価</th>
                <th class="text-center">損益評価</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% current_user.positions.each do |position| %>
                <tr>
                  <td class="text-center"><%= position.position_code(position.name) %></td>
                  <td class="text-center"><%= position.position_company(position.name) %></td>
                  <td class="text-center"><%= position.lot %>株</td>
                  <td class="text-center"><%= position.buy_price %>円</td>
                  <% @stacks.each do |stack| %>
                    <% if stack.code == position.position_code(position.name).to_i %>
                      <td class="text-center"><%= stack.stock_price %>円</td>
                      <% if (stack.stock_price - position.buy_price) * position.lot > 0 %>
                        <td class="text-center text-info"><%= (stack.stock_price - position.buy_price) * position.lot %>円</td>
                      <% else %>
                        <td class="text-center text-danger"><%= (stack.stock_price - position.buy_price) * position.lot %>円</td>
                      <% end %>
                    <% end %>
                  <% end %>
                  <td class="text-right"><%= link_to "詳細確認", position_path(position.id), class: "btn btn-primary btn-sm" %></td>
                  <td class="text-right"><%= link_to "変更", edit_position_path(position.id), class: "btn btn-success btn-sm"%></td>
                  <td class="text-right"><%= link_to "削除", position_path(position.id), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "本当に削除してよろしいですか？" } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <!-- CSVダウンロード -->
  <div class="row">
    <div class="col-xs-12">
      <div class=" text-right csv_button">
        <p><b>ポジションをダウンロードする<b>　
          <a><%= link_to 'CSVダウンロード', positions_path(format: :csv), class: "btn btn-default" %></a>
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <div class="thumbnail">
        <h3>全保有株の比率（投資金額）</h3>
        <!-- <%#= current_user.positions.each do |poaition| %> -->
        <!-- <p> (position.buy_price * position.lot). </p> -->
        <!-- <%# end %> -->
        <div class="pie_chrat">
          <!-- ここに円グラフを表示 -->
          <canvas id="myPieChart" width="300" height="300"></canvas>
        </div>
        <%= javascript_tag do %>
          var pieLabels = [
            <% current_user.positions.each do |position| %>
              '<%= "#{position.position_company(position.name)}" %>',
            <% end %>
          ];
          var pieColors =
          <%= raw(color(@positions.size)) %>
          ;
          var date = [
            <% current_user.positions.each do |position| %>
              <%= "#{position.buy_price * position.lot}," %>
            <% end %>
          ];
        <% end %>

        <%= javascript_tag do %>
          (window.onload = function(){
            var ctx = document.getElementById("myPieChart").getContext("2d");
            window.pieData = new Chart(ctx, {
              type: 'pie',
              data: {
                labels: pieLabels,
                datasets: [{
                  backgroundColor: pieColors,
                  data: date,
                }]
              }
            });
          })();
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/positions/new.html.erb
<div class="container">
  <div class="line_header">
    <h3>ポジションを作成する</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/positions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10">
      <div class="line_header">
        <h3>個別銘柄の詳細設定</h3>
      </div>
      <div class="form-horizontal">
        <div class="form-group">
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th colspan="4">証券コード、銘柄名<br>
                    <%= @position.name %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="text-center">保有株数</td>
                  <td class="text-center">買付け価格</td>
                  <td class="text-center">株価</td>
                  <td class="text-center">損益評価</td>
                </tr>
                <tr>
                  <td class="text-center"><%= @position.lot %>株</td>
                  <td class="text-center"><%= @position.buy_price %>円</td>
                  <% @stacks.each do |stack| %>
                    <% if stack.code == @position.position_code(@position.name).to_i %>
                      <td class="text-center"><%= stack.stock_price %>円</td>
                      <% if (stack.stock_price - @position.buy_price) * @position.lot > 0 %>
                        <td class="text-center text-info "><%= (stack.stock_price - @position.buy_price) * @position.lot %>円</td>
                      <% else %>
                        <td class="text-center text-danger"><%= (stack.stock_price - @position.buy_price) * @position.lot %>円</td>
                      <% end %>
                    <% end %>
                  <% end %>
                </tr>
                <tr>
                  <td colspan="4">取引理由<br>
                  <%= @position.buy_reason %>
                  </td>
                </tr>
                <!-- <p>取引理由（画像）：<%= @position.buy_image %></p> -->
                <tr>
                  <td class="text-center table_center">目標売却価格</td>
                  <td class="text-center table_center">目標売却差分</td>
                  <td class="text-center">目標上昇比率<br>（売却株価）</td>
                  <td class="text-center table_center">比率売却差分</td>
                  <!-- <td>（購入後の）最高値後からの騰落％<%= @position.high_price_per %></td> -->
                </tr>
                <tr>
                  <% @stacks.each do |stack| %>
                    <% if stack.code == @position.position_code(@position.name).to_i %>
                      <td class="text-center table_center"><%= @position.sell_price %>円</td>
                      <% if stack.stock_price - @position.sell_price > 0 %>
                        <td class="text-center info"><%= stack.stock_price - @position.sell_price %>円<br>目標達成!!</td>
                      <% else %>
                        <td class="text-center"><%= stack.stock_price - @position.sell_price %>円<br>上昇待ち</td>
                      <% end %>
                      <td class="text-center"><%= @position.sell_percent %>％<br>（<%= (@position.buy_price * ((100 + @position.sell_percent.round(2)) / 100)).to_i %>円）</td>
                      <% if stack.stock_price - (@position.buy_price * ((100 + @position.sell_percent.round(2)) / 100)).to_i > 0 %>
                        <td class="text-center info"><%= stack.stock_price - (@position.buy_price * ((100 + @position.sell_percent.round(2)) / 100)).to_i %>円<br>目標達成!!</td>
                      <% else %>
                        <td class="text-center"><%= stack.stock_price - (@position.buy_price * ((100 + @position.sell_percent.round(2)) / 100)).to_i %>円<br>上昇待ち</td>
                      <% end %>
                    <% end %>
                  <% end %>
                </tr>
                <tr>
                  <td colspan="4">売却理由<br>
                    <%= @position.sell_reason %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="text-center col-xs-offset-1 col-xs-10">
      <p><%= link_to "戻る", positions_path, class: "btn btn-default" %></p>
    </div>
  </div>
</div>