config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :positions, only: [:index, :new, :create, :edit, :show, :update, :destroy]
  resources :selections, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :companies, only: [:index, :show]

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :stacks, only: [:index]

  root 'top#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :stack

  # 検索機能（証券コードのみ）
    def self.search(search)
      if search
        Company.where(['code LIKE ?', "%#{search}"])
      else
        Company.all
      end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  def index
    # @companies = Company.all.order(:code)
    @stacks = Stack.all
    @companies = Company.page(params[:page]).order(:code)
    # if params[:search]
    #   # 検索機能（証券コードのみ）
    #   @companies = Company.search(params[:search]).page(params[:page]).order(:code)
    #   #  binding.pry
    # else
    #   # kaminari
    #   @companies = Company.page(params[:page]).order(:code)
    # end
  end

  # チャート、優待表示で使用
  # def show
  # end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="modal-diaog">
  <div class="modal-content">
  </div>
</div>

app/views/companies/index.html.erb
<% provide(:title, "｜ 上場企業一覧")%>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p class="text-center"><%= notice %></p>
      <div class="line_header">
        <h3>企業一覧</h3>
      </div>

<!-- # 検索機能 -->
<!-- <%#= form_tag companies_path, :method => 'get' do %>
<p>
  <%#= text_field_tag :search, params[:search] %>
  <%#= submit_tag "Search", :code => nil %>
</p>
<%# end %> -->
<!-- 検索機能ここまで -->

      <!-- ページネーション -->
      <p><%= paginate @companies %></p>
      <!-- ページネーションここまで -->
      <div class="thumbnail position_table">
        <div class="alt_table_responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <!-- 現在の非表示は財務表作成後、表示予定 -->
                <th class="text-center table_center">証券コード</th>
                <th class="text-center table_center">会社名</th>
                <th class="text-center table_center">市場</th>
                <th class="text-center table_center">業種</th>
                <th class="text-center table_center">株価</th>
                <th class="text-center table_center">時価総額<br>(百万円)</th>
                <th class="text-center table_center">発行株式数</th>
                <th class="text-center table_center">EPS</th>
                <th class="text-center table_center">BPS</th>
                <th class="text-center table_center">配当金</th>
                <th class="text-center table_center">配当利回り</th>
                <th class="text-center table_center">PER</th>
                <th class="text-center table_center">適正株価</th>
                <th class="text-center table_center">業種別<br>PER</th>
                <th class="text-center table_center">業種別<br>適正株価</th>
                <th class="text-center table_center">PBR</th>
                <!-- <th class="text-center table_center">ROA</th> -->
                <th class="text-center table_center">ROE</th>
                <!-- <th class="text-center table_center">PSR</th> -->
                <!-- <th class="text-center table_center">PCFR</th> -->
                <!-- <th class="text-center table_center">PEGレシオ</th> -->
                <th class="text-center table_center">期待収益率</th>
                <th class="text-center table_center">配当性向</th>
                <th class="text-center table_center">ミックス係数</th>
                <th class="text-center table_center">優待内容</th>
                <th class="text-center table_center" colspan="2" >優待権利日</th>
                <th class="text-center table_center">長期間優待</th>
                <th class="text-center table_center">優待金額</th>
                <th class="text-center table_center">優待利回り</th>
                <th class="text-center table_center">総合利回り</th>
                <th class="text-center table_center">(最低)優待<br>単元数</th>
                <!-- <th class="text-center table_center">会社HP<br>IR情報</th> -->
              </tr>
            </thead>
            <tbody>
              <% @companies.each do |company| %>
                <tr>
                  <!-- データー設定予定、データーそのものはある -->
                  <td class="text-left"><%= company.code %></td><!-- 証券コード -->
                  <td class="text-left"><%= company.company.slice(0..6) %></td><!-- 会社名 -->
                  <% @stacks.each do |stack| %>
                    <% if company.code == stack.code %>
                      <td class="text-left"><%= stack.market %></td><!-- 市場(API) -->
                      <td class="text-left"><%= stack.sector %></td><!-- 業種(API) -->
                      <td class="text-right"><%= stack.stock_price %></td><!-- 株価(API) -->
                      <td class="text-right"><%= stack.market_price %></td><!-- 時価総額(API) -->
                      <td class="text-right"><%= stack.issued_stocks %></td><!-- 発行株式数(API) -->
                      <td class="text-right"><%= stack.eps %></td><!-- EPS(API) -->
                      <td class="text-right"><%= stack.bps %></td><!-- BPS(API) 命名間違えた -->
                      <td class="text-right"><%= stack.dividend %></td><!-- 配当金(API) -->
                      <td class="text-right"><%= (stack.dividend / stack.stock_price * 100).round(2) %> ％</td><!-- 配当利回り (計算) -->
                      <td class="text-right"><%= stack.eps == 0 ? "-" : (stack.stock_price / stack.eps).round(2)  %></td><!-- PER (設定) -->
                      <td class="text-right"><%= (stack.eps * company.set_per).to_i %></td><!-- 適正株価 (計算) -->
                      <td class="text-right"><%= stack.industry_per %></td><!-- 業種別PER(API) -->
                      <td class="text-right"><%= (stack.eps * stack.industry_per).to_i %></td><!-- 適正株価(業種別PER) (計算) -->
                      <td class="text-right"><%= stack.bps == 0 ? "0" : (stack.stock_price / stack.bps).round(2) %></td><!-- PBR (計算) -->
                      <!-- <td class="text-right"><%=  %></td> --><!-- ROA (計算:純利益/総資本*100) -->
                      <td class="text-right"><%= stack.bps == 0 ? "0" : (stack.eps / stack.bps * 100).round(2) %></td><!-- ROE (計算) -->
                      <!-- <td class="text-right"><%=  %></td> --><!-- PSR (計算:時価総額/売上高) -->
                      <!-- <td class="text-right"><%=  %></td> --><!-- PCFR (計算:株価/(営業キャッシュフロー/発行株式数)) -->
                      <!-- <td class="text-right"><%=  %></td> --><!-- PEGレシオ (計算:PER/営業利益や経常利益の成長率) -->
                      <td class="text-right"><%= (stack.eps / stack.stock_price * 100).round(2) %> ％</td><!-- 期待収益率 (計算) -->
                      <td class="text-right"><%= stack.eps == 0 ? "-" : (stack.dividend / stack.eps * 100).to_i %> ％</td><!-- 配当性向 (計算) -->
                      <td class="text-right"><%= stack.eps == 0 ? "-" : (stack.stock_price / stack.bps * stack.stock_price / stack.eps).round(2) %></td><!-- ミックス係数 (計算) -->
                    <% end %>
                  <% end %>
                  <!-- company.yutai 優待内容　モーダル作成位置 -->
                  <td class="text-center"><%= company.yutai_simple == "0" ? "-" : company.yutai_simple %></td><!-- 優待内容(簡略) -->
                  <!-- <td class="text-center"><%#= company.yutai_simple == "0" ? "-" : link_to company.month_before, company_path(company.id), remote: true %></td> --><!-- 優待内容(簡略) -->
                  <!-- <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div> -->
                  <!-- ここまで -->
                  <td class="text-center"><%= company.month_before == "0" ? "" : company.month_before %></td><!-- 優待権利日 -->
                  <td class="text-center"><%= company.month_rear == "0" ? "" : company.month_rear %></td><!-- 優待権利日 -->
                  <td class="text-center"><%= company.long_term == true ? "◯" : "-" %></td><!-- 長期間優待 -->
                  <td class="text-right"><%= company.yutai_simple == "0" ? "-" : "#{company.money} 円" %></td><!-- 優待金額 -->
                  <% @stacks.each do |stack| %>
                    <% if company.code == stack.code %>
                      <td class="text-right"><%= company.yutai_simple == "0" ? "-" : "#{(company.money / (stack.stock_price * company.share_unit).to_f * 100).round(2)} ％" %></td><!-- 優待利回り (計算) -->
                      <td class="text-right"><%= stack.dividend.to_i == 0 ? (company.money / (stack.stock_price * company.share_unit) * 100).round(2) :
                       (stack.dividend / stack.stock_price * 100 + company.money / (stack.stock_price * company.share_unit).to_f * 100).round(2) %> ％</td><!-- 総合利回り (計算) -->
                    <% end %>
                  <% end %>
                  <td class="text-right"><%= company.yutai_simple == "0" ? "-" : "#{company.share_unit} 株" %></td><!-- 優待最低単元数 -->
                  <!-- <td class="text-center"><%#= link_to "IR情報を見る", company.site, :target=>["_blank"] %></td> --><!-- 会社HPのIR（別タブ） -->
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <!-- 下段のページネーション -->
      <p><%= paginate @companies %></p>
    </div>
  </div>
</div>

app/views/companies/show.js.erb
$("#user-modal").html("<%= escape_javascript(render 'form') %>")
$("#user-modal").modal("show")