config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :positions, only: [:index, :new, :create, :edit, :show, :update, :destroy]
  resources :selections, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :companies, only: [:index, :show]

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :stacks, only: [:index]

  root 'top#index'

end

app/models/selection.rb
class Selection < ActiveRecord::Base
  validates :selection_order, :buy_selection, :terget_price, presence: true

  belongs_to :user
  belongs_to :stack

  #証券コードを表示
  def selection_code(stack_code)
    stack_code.slice(0,4)
  end

  # 会社名を表示
  def selection_company(stack_company)
    stack_company.slice(4..14)
  end

  # csvダウンロード用
  def self.to_csv
    CSV.generate do |csv|
      csv << csv_column_selections
      all.each do |selection|
        csv << selection.csv_column_value_selections
      end
    end
  end

  # csvのヘッダーの並び順
  def self.csv_column_selections
    ["順位", "企業", "希望株価", "買い理由"]
  end

  # csvの並び順
  def csv_column_value_selections
    [selection_order, name, terget_price, buy_selection]
  end

end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_selection, only: [:edit, :update, :destroy]
  def index
    @selections = Selection.all.order(:selection_order)
    @stacks = Stack.all
    @users = User.all
    @selection_csv = current_user.selections.order(:selection_order)
    # CSV出力
    respond_to do |format|
      format.html
      format.csv {send_data @selection_csv.to_csv}
    end
  end

  def new
    @selection = Selection.new
  end

  def create
    @selection = Selection.new(selection_params)
    @selection.user_id = current_user.id
    if @selection.save
      redirect_to selections_path, notice: "投資候補を作成しました。"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @selection.update(selection_params)
      redirect_to selections_path, notice: "投資候補を更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @selection.destroy
    redirect_to selections_path, notice: "投資候補を削除しました。"
  end

  private
  def selection_params
    params.require(:selection).permit(:selection_order, :buy_selection, :terget_price, :name)
  end

  def set_selection
    @selection = Selection.find(params[:id])
  end

end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<div class="thumbnail">
  <%= form_for(@selection) do |f| %>
    <% if @selection.errors.any? %>
      <div id="error_explanation" >
        <!-- バリデーションのエラー件数 -->
        <h2><%= @selection.errors.count %>件のエラーがあります。</h2>

        <ul>
          <% @selection.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label "優先順位", class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.number_field :selection_order, min: "1", class: "form-control", placeholder: "selection_order" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "銘柄", class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.select :name, Stack.all.map{|t| ["#{t.code} #{t.company}", "#{t.code} #{t.company}"]},{},{class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "選定理由", class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.text_field :buy_selection, class: "form-control", placeholder: "buy_selection" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "購入価格（予定）", class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.number_field :terget_price, min: "1", class: "form-control", placeholder: "terget_price" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit "保存", class: "btn btn-primary" %>
          <%= link_to "戻る", selections_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/selections/edit.html.erb
<div class="container">
  <div class="line_header">
    <h3>投資予定を変更する</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/selections/index.html.erb
<% provide(:title, "｜ 投資候補一覧")%>

<!-- 個人のみ閲覧可能 -->
<div class="container">
  <div class="row">
    <div class="col">
      <p class="text-center"><%= notice %></p>
      <div class="line_header">
        <h3>投資候補先の一覧</h3>
      </div>
      <div class="thumbnail position_table">
        <p><%= link_to "候補を記録する", new_selection_path, class: "btn btn-primary position_add" %></p>
        <p>現在の候補</p>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="row"></th>
                <th class="text-center">候補順位</th>
                <th class="text-center">証券コード</th>
                <th class="text-center">会社名</th>
                <th class="text-center">購入予定株価</th>
                <th class="text-center">株価</th>
              </tr>
            </thead>
            <% current_user.selections.each do |selection| %>
              <tbody>
                <tr>
                  <th scope="row"></th>
                  <td class="text-center"><%= selection.selection_order %></td>
                  <td class="text-center"><%= selection.selection_code(selection.name) %></td>
                  <td class="text-center"><%= selection.selection_company(selection.name) %></td>
                  <td class="text-center"><%= selection.terget_price %>円</td>
                  <% @stacks.each do |stack| %>
                    <% if stack.code == selection.selection_code(selection.name).to_i %>
                      <% if stack.stock_price < selection.terget_price %>
                        <td class="text-center success"><%= stack.stock_price %>円</td>
                      <% else %>
                        <td class="text-center"><%= stack.stock_price %>円</td>
                      <% end %>
                    <% end %>
                  <% end %>
                </tr>
                <tr>
                  <th scope="row">選定理由</th>
                  <td colspan="5"><%= selection.buy_selection %></td>
                </tr>
                <tr>
                  <th scope="row"></th>
                  <td colspan="4"></td>
                  <td class="text-center"><%= link_to "変更", edit_selection_path(selection.id), class: "btn btn-success btn-sm" %>
                    <%= link_to "削除", selection_path(selection.id), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "本当に削除してよろしいですか？" } %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
      <p class="help-block">※購入予定株価より株価が下回れば緑色になります。</p>
    </div>
  </div>
</div>

  <!-- CSVダウンロード -->
  <div class="row">
    <div class="col-xs-12">
      <div class=" text-right csv_button">
        <p><b>候補一覧（詳細）をダウンロードする<b>　
          <a><%= link_to 'CSVダウンロード', selections_path(format: :csv), class: "btn btn-default" %></a>
        </p>
      </div>
    </div>
  </div>

app/views/selections/new.html.erb
<div class="container">
  <div class="line_header">
    <h3>購入候補を作成する</h3>
  </div>
  <%= render 'form' %>
</div>