config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :positions, only: [:index, :new, :create, :edit, :show, :update, :destroy]
  resources :selections, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :companies, only: [:index, :show]

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :stacks, only: [:index]

  root 'top#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stock-Note <%= yield(:title)%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- chart.js用 -->
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <!-- 組み込み用のコードを使用 -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.js"></script>

</head>
<body>
  <header>
    <nav class="navbar navbar-default drop_menu">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Stack-Note", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav drop_menu">
            <% if user_signed_in? %>
              <li><%= link_to "ポートフォリオ", positions_path %></li>
              <li><%= link_to "投資候補一覧", selections_path %></li>
              <li><%= link_to "上場企業一覧", companies_path %></li>
              <!-- <li><%= link_to "取引結果 - 工事中 -", root_path %></li> -->
              <!-- <li><%= link_to "取引手法 - 工事中 -", root_path %></li> -->
              <li><%= link_to "マイページ", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "サインアップ", new_user_registration_path %></li>
              <!-- <li><%= link_to "お問い合わせ", new_contact_path %></li> -->
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

<%= yield %>

  <footer>
    <div class=footer>
    <p>2017-2017 StockNote</p>
  </div>
  </footer>
</body>
</html>